### PR TITLE
document a way to get Prax.cr on Arch Linux

### PR DESCRIPTION
**Pull request by tijn**
I adapted the Debian scripts to make Prax run on Arch Linux.

I would like to automate the whole installation, but that involves spending more time on it than I can currently invest in this. Therefore I opted to do the next best thing I could come up with: I wrote a small readme file to describe where every file should go and how it all ties together.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Quite a lot of work here. A PKGBUILD would be great, but I understand you don't have time.

Could you escape the `*.dev` in the README so it's not parsed as an emphasis by markdown? then squash your commits into a single one?

**Comment by adamcrown** [comment]
This would be great. I've got prax running on Arch now and have been meaning to switch to prax.cr

**Comment by tijn** [comment]
@ysbaddaden yes, will do :-)

@adamcrown do you happen to know how to make PKGBUILD files? I've never done it but I'll probably try to make one anyway. It might take a while though.

**Comment by ysbaddaden** [comment]
BTW I added the `prax iptables` command to avoid duplicating the rules for each distribution.

**Comment by adamcrown** [comment]
@ysbaddaden I never have written a PKGBUILD. I'd be happy to take a stab at it but I'm a bit busy now so it may take me a while to get to.

**Comment by tijn** [comment]
@ysbaddaden I squashed my commits and escaped the asterisks.

I decided I am going to *try* to make a PKGBUILD but I cannot seem to find the `prax iptables` command you mentioned... where should I look?

**Comment by ysbaddaden** [comment]
I forgot to push 0444c67a6b73f5effdace18151974a15c1f64f9b !

**Comment by tijn** [comment]
superseded by #41

**Comment by tijn** [comment]
@adamcrown since you specifically mentioned it: [This branch of my PKGBUILD-repo](https://github.com/tijn/prax-arch/tree/include-systemd-files) will probably make it really easy for you to switch to prax.cr on Arch. I'm using it myself right now.

**Comment by adamcrown** [comment]
Awesome! Thanks. I'll give it a try.

**Comment by ysbaddaden** [comment]
Thanks for packaging Prax for Archlinux!

I see there are some manual steps required? Could they be somewhat automated to the beat solution?

**Comment by tijn** [comment]
@ysbaddaden They can be automated, it would be really easy for the iptables-service, but as far as I know only Debian will start services right after their installation  (and Debian-derived distros). Arch users supposedly like to be able to tweak config files before they are started. It's simply a different philosophy.

**Comment by ysbaddaden** [comment]
OK.

**Pull request closed without merging**
