### PR TITLE
Replace defunct xip.io with nip.io

### PR DESCRIPTION
**Pull request by graywh**
xip.io is dead, nip.io does the same thing

### CODE REVIEW

**Review by ysbaddaden — APPROVED** [review]

**Comment by ysbaddaden** [comment]
Thank you, I didn't notice xip.io was defunct.

This is good, but could you fix the README and tests, too?
See for example https://github.com/ysbaddaden/prax.cr/search?q=xip.io

**Comment by graywh** [comment]
Sorry, totally overlooked non-source files.

Yeah, apparently it's been gone for a few months.  I only realized yesterday.

Would you rather have a more generic solution that doesn't require such a specific match?  Maybe even just relying on Array#pop until a matching site is found?

**Review by ysbaddaden — APPROVED** [review]

**Comment by ysbaddaden** [comment]
It's fine. The issue is fixed now.

**Comment by graywh** [comment]
Just noticed I accidentally replaced an "assert" with ":ssert"

**Comment by graywh** [comment]
Could use a new .deb release with this feature.

**Pull request merged**
